-- MySQL Script generated by MySQL Workbench
-- Wed Dec  4 08:53:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `clt_id` INT NOT NULL AUTO_INCREMENT,
  `clt_nombre_usuario` VARCHAR(50) NULL,
  `clt_nombre_completo` VARCHAR(300) NULL,
  `clt_curp` CHAR(18) NULL,
  `clt_correo` VARCHAR(300) NULL,
  `clt_contraseña` VARCHAR(100) NULL,
  `clt_fecha_registro` DATE NULL,
  PRIMARY KEY (`clt_id`),
  UNIQUE INDEX `clt_nombre_usuario_UNIQUE` (`clt_nombre_usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Numero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Numero` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Numero` (
  `idNumero` INT NOT NULL,
  `idCliente` INT NULL,
  `numeroTelefono` INT NULL,
  PRIMARY KEY (`idNumero`),
  INDEX `idCliente_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Direccion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Direccion` (
  `dir_id` INT NOT NULL AUTO_INCREMENT,
  `dir_direccion` VARCHAR(512) NULL,
  `dir_ciudad` VARCHAR(200) NULL,
  `dir_estado` VARCHAR(100) NULL,
  `dir_codigo_postal` CHAR(5) NULL,
  `dir_clt_id` INT NOT NULL,
  PRIMARY KEY (`dir_id`),
  INDEX `fk_Direccion_Cliente1_idx` (`dir_clt_id` ASC) VISIBLE,
  CONSTRAINT `fk_Direccion_Cliente1`
    FOREIGN KEY (`dir_clt_id`)
    REFERENCES `mydb`.`Cliente` (`clt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Renta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Renta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Renta` (
  `rnt_id` INT NOT NULL AUTO_INCREMENT,
  `rnt_fecha` DATE NULL,
  `rnt_hora` TIME NULL,
  `rnt_precio` DECIMAL NULL,
  `rnt_compensacion` DECIMAL NULL,
  `rnt_dir_id` INT NOT NULL,
  `rnt_clt_id` INT NOT NULL,
  PRIMARY KEY (`rnt_id`),
  INDEX `fk_Renta_Direccion1_idx` (`rnt_dir_id` ASC) VISIBLE,
  INDEX `fk_Renta_Cliente2_idx` (`rnt_clt_id` ASC) VISIBLE,
  UNIQUE INDEX `rnt_hora_UNIQUE` (`rnt_hora` ASC) VISIBLE,
  CONSTRAINT `fk_Renta_Direccion1`
    FOREIGN KEY (`rnt_dir_id`)
    REFERENCES `mydb`.`Direccion` (`dir_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Renta_Cliente2`
    FOREIGN KEY (`rnt_clt_id`)
    REFERENCES `mydb`.`Cliente` (`clt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TipoItem` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TipoItem` (
  `idTipoItem` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoItem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Item` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Item` (
  `itm_id` INT NOT NULL AUTO_INCREMENT,
  `itm_nombre` VARCHAR(80) NULL,
  `itm_ancho` DECIMAL NULL,
  `itm_alto` DECIMAL NULL,
  `itm_largo` DECIMAL NULL,
  `itm_precio` DECIMAL NULL,
  `itm_cantidad_disponible` INT NULL,
  `itm_cantidad_total` INT NULL,
  `itm_tip_id` INT NOT NULL,
  PRIMARY KEY (`itm_id`),
  INDEX `fk_Item_Tipo_item1_idx` (`itm_tip_id` ASC) VISIBLE,
  CONSTRAINT `fk_Item_Tipo_item1`
    FOREIGN KEY (`itm_tip_id`)
    REFERENCES `mydb`.`Tipo_item` (`tip_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`relDireccionCliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`relDireccionCliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`relDireccionCliente` (
  `idrelDireccionCliente` INT NOT NULL,
  `idDireccion` INT NULL,
  `idCliente` INT NULL,
  PRIMARY KEY (`idrelDireccionCliente`),
  INDEX `idDireccion_idx` (`idDireccion` ASC) VISIBLE,
  INDEX `idCliente_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `idDireccion`
    FOREIGN KEY (`idDireccion`)
    REFERENCES `mydb`.`Direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RelRentaItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`RelRentaItem` ;

CREATE TABLE IF NOT EXISTS `mydb`.`RelRentaItem` (
  `idRelRentaItem` INT NOT NULL,
  `idRenta` INT NOT NULL,
  `idItem` INT NOT NULL,
  `cantItem` INT NULL,
  PRIMARY KEY (`idRelRentaItem`, `idRenta`, `idItem`),
  INDEX `idRenta_idx` (`idRenta` ASC) VISIBLE,
  INDEX `idItem_idx` (`idItem` ASC) VISIBLE,
  CONSTRAINT `idRenta`
    FOREIGN KEY (`idRenta`)
    REFERENCES `mydb`.`Renta` (`idRenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idItem`
    FOREIGN KEY (`idItem`)
    REFERENCES `mydb`.`Item` (`idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CompensaciónItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CompensaciónItem` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CompensaciónItem` (
  `idCompensaciónItem` INT NOT NULL,
  `idItem` INT NOT NULL,
  `idRenta` INT NOT NULL,
  `cantItemCompensacion` INT NULL,
  PRIMARY KEY (`idCompensaciónItem`, `idRenta`, `idItem`),
  INDEX `idItem_idx` (`idItem` ASC) VISIBLE,
  INDEX `idRenta_idx` (`idRenta` ASC) VISIBLE,
  CONSTRAINT `idItem`
    FOREIGN KEY (`idItem`)
    REFERENCES `mydb`.`Item` (`idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idRenta`
    FOREIGN KEY (`idRenta`)
    REFERENCES `mydb`.`Renta` (`idRenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `clt_id` INT NOT NULL AUTO_INCREMENT,
  `clt_nombre_usuario` VARCHAR(50) NULL,
  `clt_nombre_completo` VARCHAR(300) NULL,
  `clt_curp` CHAR(18) NULL,
  `clt_correo` VARCHAR(300) NULL,
  `clt_contraseña` VARCHAR(100) NULL,
  `clt_fecha_registro` DATE NULL,
  PRIMARY KEY (`clt_id`),
  UNIQUE INDEX `clt_nombre_usuario_UNIQUE` (`clt_nombre_usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefono`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Telefono` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Telefono` (
  `tel_id` INT NOT NULL AUTO_INCREMENT,
  `tel_numero` CHAR(10) NOT NULL,
  `tel_clt_id` INT NOT NULL,
  PRIMARY KEY (`tel_id`),
  INDEX `fk_Telefono_Cliente1_idx` (`tel_clt_id` ASC) VISIBLE,
  CONSTRAINT `fk_Telefono_Cliente1`
    FOREIGN KEY (`tel_clt_id`)
    REFERENCES `mydb`.`Cliente` (`clt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Direccion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Direccion` (
  `dir_id` INT NOT NULL AUTO_INCREMENT,
  `dir_direccion` VARCHAR(512) NULL,
  `dir_ciudad` VARCHAR(200) NULL,
  `dir_estado` VARCHAR(100) NULL,
  `dir_codigo_postal` CHAR(5) NULL,
  `dir_clt_id` INT NOT NULL,
  PRIMARY KEY (`dir_id`),
  INDEX `fk_Direccion_Cliente1_idx` (`dir_clt_id` ASC) VISIBLE,
  CONSTRAINT `fk_Direccion_Cliente1`
    FOREIGN KEY (`dir_clt_id`)
    REFERENCES `mydb`.`Cliente` (`clt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Renta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Renta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Renta` (
  `rnt_id` INT NOT NULL AUTO_INCREMENT,
  `rnt_fecha` DATE NULL,
  `rnt_hora` TIME NULL,
  `rnt_precio` DECIMAL NULL,
  `rnt_compensacion` DECIMAL NULL,
  `rnt_dir_id` INT NOT NULL,
  `rnt_clt_id` INT NOT NULL,
  PRIMARY KEY (`rnt_id`),
  INDEX `fk_Renta_Direccion1_idx` (`rnt_dir_id` ASC) VISIBLE,
  INDEX `fk_Renta_Cliente2_idx` (`rnt_clt_id` ASC) VISIBLE,
  UNIQUE INDEX `rnt_hora_UNIQUE` (`rnt_hora` ASC) VISIBLE,
  CONSTRAINT `fk_Renta_Direccion1`
    FOREIGN KEY (`rnt_dir_id`)
    REFERENCES `mydb`.`Direccion` (`dir_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Renta_Cliente2`
    FOREIGN KEY (`rnt_clt_id`)
    REFERENCES `mydb`.`Cliente` (`clt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tipo_item` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_item` (
  `tip_id` INT NOT NULL AUTO_INCREMENT,
  `tip_tipo_item` VARCHAR(45) NULL,
  PRIMARY KEY (`tip_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Item` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Item` (
  `itm_id` INT NOT NULL AUTO_INCREMENT,
  `itm_nombre` VARCHAR(80) NULL,
  `itm_ancho` DECIMAL NULL,
  `itm_alto` DECIMAL NULL,
  `itm_largo` DECIMAL NULL,
  `itm_precio` DECIMAL NULL,
  `itm_cantidad_disponible` INT NULL,
  `itm_cantidad_total` INT NULL,
  `itm_tip_id` INT NOT NULL,
  PRIMARY KEY (`itm_id`),
  INDEX `fk_Item_Tipo_item1_idx` (`itm_tip_id` ASC) VISIBLE,
  CONSTRAINT `fk_Item_Tipo_item1`
    FOREIGN KEY (`itm_tip_id`)
    REFERENCES `mydb`.`Tipo_item` (`tip_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_item_renta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tipo_item_renta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_item_renta` (
  `tir_id` INT NOT NULL AUTO_INCREMENT,
  `tir_tipo` VARCHAR(50) NULL,
  PRIMARY KEY (`tir_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Item_renta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Item_renta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Item_renta` (
  `itr_id` INT NOT NULL AUTO_INCREMENT,
  `itr_rnt_id` INT NOT NULL,
  `itr_itm_id` INT NOT NULL,
  `itr_cantidad` INT NULL,
  `itr_tir_id` INT NOT NULL,
  PRIMARY KEY (`itr_id`, `itr_rnt_id`, `itr_itm_id`),
  INDEX `fk_Item_renta_Renta1_idx` (`itr_rnt_id` ASC) VISIBLE,
  INDEX `fk_Item_renta_Item1_idx` (`itr_itm_id` ASC) VISIBLE,
  INDEX `fk_Item_renta_Tipo_item_renta1_idx` (`itr_tir_id` ASC) VISIBLE,
  CONSTRAINT `fk_Item_renta_Renta1`
    FOREIGN KEY (`itr_rnt_id`)
    REFERENCES `mydb`.`Renta` (`rnt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_renta_Item1`
    FOREIGN KEY (`itr_itm_id`)
    REFERENCES `mydb`.`Item` (`itm_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_renta_Tipo_item_renta1`
    FOREIGN KEY (`itr_tir_id`)
    REFERENCES `mydb`.`Tipo_item_renta` (`tir_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
