-- MySQL Script generated by MySQL Workbench
-- Thu Dec  5 13:13:51 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema feeast
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `feeast` ;

-- -----------------------------------------------------
-- Schema feeast
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `feeast` DEFAULT CHARACTER SET utf8 ;
USE `feeast` ;

-- -----------------------------------------------------
-- Table `feeast`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `feeast`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `feeast`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NULL,
  `nombreCliente` VARCHAR(300) NULL,
  `CURP` CHAR(18) NULL,
  `correo` VARCHAR(300) NULL,
  `password` VARCHAR(100) NULL,
  `fechaRegistro` DATETIME NULL default current_timestamp(),	#################################################################################
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `clt_nombre_usuario_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feeast`.`Telefono`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `feeast`.`Telefono` ;

CREATE TABLE IF NOT EXISTS `feeast`.`Telefono` (
  `idTelefono` INT NOT NULL AUTO_INCREMENT,
  `numero` CHAR(10) NOT NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idTelefono`),
  INDEX `fk_Telefono_Cliente1_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Telefono_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `feeast`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feeast`.`Direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `feeast`.`Direccion` ;

CREATE TABLE IF NOT EXISTS `feeast`.`Direccion` (
  `idDireccion` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(512) NULL,
  `ciudad` VARCHAR(200) NULL,
  `estado` VARCHAR(100) NULL,
  `codigoPostal` CHAR(5) NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idDireccion`),
  INDEX `fk_Direccion_Cliente1_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Direccion_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `feeast`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feeast`.`Renta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `feeast`.`Renta` ;

CREATE TABLE IF NOT EXISTS `feeast`.`Renta` (
  `idRenta` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `hora` TIME NULL,
  `precio` DECIMAL NULL,
  `compensacion` DECIMAL NULL,
  `estado` VARCHAR(20) NOT NULL DEFAULT 'Pendiente',		#################################################################################
  `comentario` varchar(250) NULL,							#################################################################################
  `idDireccion` INT NOT NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idRenta`),
  INDEX `fk_Renta_Direccion1_idx` (`idDireccion` ASC) VISIBLE,
  INDEX `fk_Renta_Cliente2_idx` (`idCliente` ASC) VISIBLE,
  UNIQUE INDEX `rnt_hora_UNIQUE` (`hora` ASC) VISIBLE,
  CONSTRAINT `fk_Renta_Direccion1`
    FOREIGN KEY (`idDireccion`)
    REFERENCES `feeast`.`Direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Renta_Cliente2`
    FOREIGN KEY (`idCliente`)
    REFERENCES `feeast`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feeast`.`TipoItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `feeast`.`TipoItem` ;

CREATE TABLE IF NOT EXISTS `feeast`.`TipoItem` (
  `idTipoItem` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoItem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feeast`.`Item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `feeast`.`Item` ;

CREATE TABLE IF NOT EXISTS `feeast`.`Item` (
  `idItem` INT NOT NULL AUTO_INCREMENT,
  `nombreItem` VARCHAR(80) NULL,
  `ancho` FLOAT NULL,
  `alto` FLOAT NULL,
  `largo` FLOAT NULL,
  `precio` DECIMAL NULL,
  `cantidadDisponible` INT NULL,
  `cantidadTotal` INT NULL,
  `idTipo` INT NOT NULL,
  PRIMARY KEY (`idItem`),
  INDEX `fk_Item_Tipo_item1_idx` (`idTipo` ASC) VISIBLE,
  CONSTRAINT `fk_Item_Tipo_item1`
    FOREIGN KEY (`idTipo`)
    REFERENCES `feeast`.`TipoItem` (`idTipoItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feeast`.`Tipo_item_renta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `feeast`.`Tipo_item_renta` ;

CREATE TABLE IF NOT EXISTS `feeast`.`Tipo_item_renta` (
  `idTipoItemRenta` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(50) NULL,
  PRIMARY KEY (`idTipoItemRenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feeast`.`Item_renta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `feeast`.`Item_renta` ;

CREATE TABLE IF NOT EXISTS `feeast`.`Item_renta` (
  `idItemRenta` INT NOT NULL AUTO_INCREMENT,
  `idRenta` INT NOT NULL,
  `idItem` INT NOT NULL,
  `cantItem` INT NULL,
  `idTipoItemRenta` INT NOT NULL,
  PRIMARY KEY (`idItemRenta`, `idRenta`, `idItem`),
  INDEX `fk_Item_renta_Renta1_idx` (`idRenta` ASC) VISIBLE,
  INDEX `fk_Item_renta_Item1_idx` (`idItem` ASC) VISIBLE,
  INDEX `fk_Item_renta_Tipo_item_renta1_idx` (`idTipoItemRenta` ASC) VISIBLE,
  CONSTRAINT `fk_Item_renta_Renta1`
    FOREIGN KEY (`idRenta`)
    REFERENCES `feeast`.`Renta` (`idRenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_renta_Item1`
    FOREIGN KEY (`idItem`)
    REFERENCES `feeast`.`Item` (`idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_renta_Tipo_item_renta1`
    FOREIGN KEY (`idTipoItemRenta`)
    REFERENCES `feeast`.`Tipo_item_renta` (`idTipoItemRenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
